package models

enum class tipoResiduo(valor: String) {
    RESTO("RESTO"),
    ENVASES("ENVASES"),
    VIDRIO("VIDRIO"),
    VIDRIO_COMERCIAL("VIDRIO COMERCIAL"),
    CLINICOS("CLINICOS"),
    ORGANICA("ORGÁNICA"),
    PAPEL_CARTON("PAPEL-CARTON"),
    CARTON_COMERCIAL("CARTON COMERCIAL"),
    RCD("RCD"),
    PUNTOS_LIMPIOS("PUNTOS LIMPIOS"),
    CONTENEDORES_DE_ROPA("CONTENEDORES DE ROPA"),
    CAMA_DE_CABALLO("CAMA DE CABALLO"),
    PILAS("PILAS"),
    ANIMALES_MUERTOS("ANIMALES MUERTOS")
}